# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Santiago"
license = "MIT"
licenselink = "https://github.com/mstrandgren/santiago/blob/master/LICENSE.md"
description = "Really minimal blog theme for hugo"
homepage = "https://github.com/mstrandgren/santiago"
tags = ["blog", "font awesome"]
features = ["html5", "css3", "tags"]
min_version = 0.16

[author]
  name = "Martin Strandgren"
  homepage = "https://github.com/mstrandgren"
